import type {Header, HeaderState} from "./app/type/Type.ts";
import JsGrid from "./app/JsGrid.tsx";
import {useCallback, useMemo, useState} from "react";
import {applyHeaderStateToHeader} from "./app/index.ts";

const PAGE_SIZE = 15;
const TOTAL_ELEMENTS = 150;
const TOTAL_PAGES = 10;

const App = () => {
    const [pageNumber, setPageNumber] = useState(0);
    const [header, setHeader] = useState<Header[]>(() => [
        {
            "key": "assetCode",
            "label": "자산코드",
            "type": "string",
            "width": 105
        },
        {
            "key": "groupName",
            "label": "자산그룹",
            "type": "string",
            "width": 104
        },
        {
            "key": "taskName",
            "label": "업무그룹",
            "type": "string",
            "width": 140
        },
        {
            "key": "assetName",
            "label": "자산명",
            "type": "string",
            "width": 338
        },
        {
            "key": "locationName",
            "label": "자산위치",
            "type": "string",
            "width": 140
        },
        {
            "key": "slaGroupName",
            "label": "SLA 그룹",
            "type": "string",
            "width": 140
        },
        {
            "key": "projectName",
            "label": "프로젝트코드",
            "type": "string",
            "width": 140
        },
        {
            "key": "mngSecondaryName",
            "label": "2차 업체",
            "type": "string",
            "width": 140
        },
        {
            "key": "importDate",
            "label": "도입일자",
            "type": "string",
            "width": 140
        },
        {
            "key": "importPrice",
            "label": "도입금액",
            "type": "string",
            "width": 140
        },
        {
            "key": "mngPrice",
            "label": "유지보수액",
            "type": "string",
            "width": 140
        },
        {
            "key": "operator",
            "label": "운영담당자",
            "type": "string",
            "width": 140
        },
        {
            "key": "handler",
            "label": "자산사용자",
            "type": "string",
            "width": 140
        },
        {
            "key": "createdAt",
            "label": "등록일",
            "type": "string",
            "width": 140
        },
        {
            "key": "updatedAt",
            "label": "수정일",
            "type": "string",
            "width": 140
        },
        {
            "key": "assetCustomCodes_146",
            "label": "IP(하드웨어)",
            "type": "string",
            "width": 140
        },
        {
            "key": "assetCustomCodes_101",
            "label": "IP(NAS)",
            "type": "string",
            "width": 140
        },
        {
            "key": "assetCustomCodes_1",
            "label": "자산유형",
            "type": "string",
            "width": 140
        },
        {
            "key": "assetCustomCodes_5",
            "label": "자산유형비고",
            "type": "string",
            "width": 140
        },
        {
            "key": "assetCustomCodes_34",
            "label": "공통코드(테스트용)",
            "type": "string",
            "width": 140
        },
        {
            "key": "assetCustomCodes_10",
            "label": "기타작업",
            "type": "string",
            "width": 140
        },
        {
            "key": "assetCustomCodes_9",
            "label": "기타",
            "type": "string",
            "width": 140
        },
        {
            "key": "assetCustomCodes_102",
            "label": "IP(HB)",
            "type": "string",
            "width": 140
        },
        {
            "key": "assetCustomCodes_91",
            "label": "IP(백업)",
            "type": "children",
            "width": 140
        },
        {
            "key": "assetCustomCodes_90",
            "label": "IP(서비스)",
            "type": "children",
            "width": 140
        },
        {
            "key": "assetCustomStrings_1",
            "label": "상태정보",
            "type": "children",
            "width": 140
        },
        {
            "key": "assetCustomStrings_2",
            "label": "테스트정보",
            "type": "children",
            "width": 140
        },
        {
            "key": "assetCustomStrings_6",
            "label": "정보",
            "type": "children",
            "width": 140
        },
        {
            "key": "assetCustomStrings_15",
            "label": "설치일자",
            "type": "children",
            "width": 140
        },
        {
            "key": "assetCustomStrings_17",
            "label": "폐기일자",
            "type": "children",
            "width": 140
        },
        {
            "key": "assetCustomStrings_16",
            "label": "서비스개시일자",
            "type": "children",
            "width": 140
        },
        {
            "key": "assetCustomStrings_7",
            "label": "도입일자",
            "type": "children",
            "width": 140
        },
        {
            "key": "assetCustomStrings_27",
            "label": "담당업체",
            "type": "children",
            "width": 140
        },
        {
            "key": "assetCustomStrings_28",
            "label": "담당자",
            "type": "children",
            "width": 140
        }
    ]);

    // const [data] = useState(() => (
    //     Array.from({ length: PAGE_SIZE }, (_, i) => ({
    //         id: pageNumber * PAGE_SIZE + i + 1,
    //         creator: {name: "등록자"},
    //         state: "접수중",
    //         title: "제목1234123123123123 어 글쎄",
    //         number: "203123-123",
    //         createdAt: "2026-01-02",
    //         requester: {name: "관리자"},
    //         score: "35",
    //         deadLine: {endBy: "2026-04-23"},
    //         category: {name: "네트워크"},
    //         updatedAt: "2026-01-02",
    //         transTo: {title: "이관정보"},
    //     }))
    // ));

    const data = {
        "content": [
            {
                "id": 3944,
                "assetName": "000시스템",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": null,
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [
                    {
                        "id": null,
                        "asset": {
                            "id": 3944,
                            "assetName": null,
                            "assetCode": null,
                            "images": null,
                            "files": null,
                            "group": null,
                            "etc": null,
                            "task": null,
                            "location": null,
                            "slaGroup": null,
                            "department": null,
                            "project": null,
                            "operator": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "handler": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "endOfService": null,
                            "endOfServiceDiff": null,
                            "involvedIntoCompose": false,
                            "mngPrimary": null,
                            "mngSecondary": null,
                            "mngTertiary": null,
                            "importDate": null,
                            "importPrice": null,
                            "mngPrice": null,
                            "mngRate": null,
                            "assetFields": null,
                            "assetCustomCodes": null,
                            "assetCustomStrings": null,
                            "groupName": null,
                            "taskName": null,
                            "locationName": null,
                            "slaGroupName": null,
                            "departmentName": null,
                            "projectName": null,
                            "handlerName": null,
                            "operatorName": null,
                            "mngPrimaryName": null,
                            "mngSecondaryName": null,
                            "mngTertiaryName": null,
                            "createdByName": null,
                            "updatedByName": null,
                            "auth": null,
                            "removed": false
                        },
                        "code": null,
                        "value": null,
                        "isRemoved": false,
                        "keyString": 7,
                        "valueString": "2026-05-04"
                    },
                    {
                        "id": null,
                        "asset": {
                            "id": 3944,
                            "assetName": null,
                            "assetCode": null,
                            "images": null,
                            "files": null,
                            "group": null,
                            "etc": null,
                            "task": null,
                            "location": null,
                            "slaGroup": null,
                            "department": null,
                            "project": null,
                            "operator": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "handler": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "endOfService": null,
                            "endOfServiceDiff": null,
                            "involvedIntoCompose": false,
                            "mngPrimary": null,
                            "mngSecondary": null,
                            "mngTertiary": null,
                            "importDate": null,
                            "importPrice": null,
                            "mngPrice": null,
                            "mngRate": null,
                            "assetFields": null,
                            "assetCustomCodes": null,
                            "assetCustomStrings": null,
                            "groupName": null,
                            "taskName": null,
                            "locationName": null,
                            "slaGroupName": null,
                            "departmentName": null,
                            "projectName": null,
                            "handlerName": null,
                            "operatorName": null,
                            "mngPrimaryName": null,
                            "mngSecondaryName": null,
                            "mngTertiaryName": null,
                            "createdByName": null,
                            "updatedByName": null,
                            "auth": null,
                            "removed": false
                        },
                        "code": null,
                        "value": null,
                        "isRemoved": false,
                        "keyString": 15,
                        "valueString": "2026-05-04"
                    },
                    {
                        "id": null,
                        "asset": {
                            "id": 3944,
                            "assetName": null,
                            "assetCode": null,
                            "images": null,
                            "files": null,
                            "group": null,
                            "etc": null,
                            "task": null,
                            "location": null,
                            "slaGroup": null,
                            "department": null,
                            "project": null,
                            "operator": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "handler": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "endOfService": null,
                            "endOfServiceDiff": null,
                            "involvedIntoCompose": false,
                            "mngPrimary": null,
                            "mngSecondary": null,
                            "mngTertiary": null,
                            "importDate": null,
                            "importPrice": null,
                            "mngPrice": null,
                            "mngRate": null,
                            "assetFields": null,
                            "assetCustomCodes": null,
                            "assetCustomStrings": null,
                            "groupName": null,
                            "taskName": null,
                            "locationName": null,
                            "slaGroupName": null,
                            "departmentName": null,
                            "projectName": null,
                            "handlerName": null,
                            "operatorName": null,
                            "mngPrimaryName": null,
                            "mngSecondaryName": null,
                            "mngTertiaryName": null,
                            "createdByName": null,
                            "updatedByName": null,
                            "auth": null,
                            "removed": false
                        },
                        "code": null,
                        "value": null,
                        "isRemoved": false,
                        "keyString": 16,
                        "valueString": "2026-05-04"
                    },
                    {
                        "id": null,
                        "asset": {
                            "id": 3944,
                            "assetName": null,
                            "assetCode": null,
                            "images": null,
                            "files": null,
                            "group": null,
                            "etc": null,
                            "task": null,
                            "location": null,
                            "slaGroup": null,
                            "department": null,
                            "project": null,
                            "operator": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "handler": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "endOfService": null,
                            "endOfServiceDiff": null,
                            "involvedIntoCompose": false,
                            "mngPrimary": null,
                            "mngSecondary": null,
                            "mngTertiary": null,
                            "importDate": null,
                            "importPrice": null,
                            "mngPrice": null,
                            "mngRate": null,
                            "assetFields": null,
                            "assetCustomCodes": null,
                            "assetCustomStrings": null,
                            "groupName": null,
                            "taskName": null,
                            "locationName": null,
                            "slaGroupName": null,
                            "departmentName": null,
                            "projectName": null,
                            "handlerName": null,
                            "operatorName": null,
                            "mngPrimaryName": null,
                            "mngSecondaryName": null,
                            "mngTertiaryName": null,
                            "createdByName": null,
                            "updatedByName": null,
                            "auth": null,
                            "removed": false
                        },
                        "code": null,
                        "value": null,
                        "isRemoved": false,
                        "keyString": 17,
                        "valueString": "2034-05-06"
                    }
                ],
                "groupName": "업무소프트웨어",
                "taskName": "정보계",
                "locationName": "본사3층",
                "slaGroupName": "1등급",
                "departmentName": null,
                "projectName": "00운영사업",
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "윤호열",
                "updatedByName": null,
                "auth": null,
                "removed": false
            },
            {
                "id": 317,
                "assetName": "DBMS_Oracle12C_업무A_DB",
                "assetCode": "AST_00008",
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [
                    {
                        "id": 3,
                        "username": null,
                        "name": "박지훈",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    },
                    {
                        "id": 2,
                        "username": null,
                        "name": "김민수",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    },
                    {
                        "id": 1,
                        "username": null,
                        "name": "관리자",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    }
                ],
                "createdBy": null,
                "updatedBy": null,
                "handler": [
                    {
                        "id": 2,
                        "username": null,
                        "name": "김민수",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    },
                    {
                        "id": 3,
                        "username": null,
                        "name": "박지훈",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    }
                ],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-01-30 13:30:16",
                "endOfService": "2026-08-10 00:00:00",
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": "2025-08-11 00:00:00",
                "importPrice": null,
                "mngPrice": "10000000",
                "mngRate": "15%",
                "assetFields": null,
                "assetCustomCodes": [
                    {
                        "asset": {
                            "id": 317,
                            "assetName": null,
                            "assetCode": null,
                            "images": null,
                            "files": null,
                            "group": null,
                            "etc": null,
                            "task": null,
                            "location": null,
                            "slaGroup": null,
                            "department": null,
                            "project": null,
                            "operator": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "handler": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "endOfService": null,
                            "endOfServiceDiff": null,
                            "involvedIntoCompose": false,
                            "mngPrimary": null,
                            "mngSecondary": null,
                            "mngTertiary": null,
                            "importDate": null,
                            "importPrice": null,
                            "mngPrice": null,
                            "mngRate": null,
                            "assetFields": null,
                            "assetCustomCodes": null,
                            "assetCustomStrings": null,
                            "groupName": null,
                            "taskName": null,
                            "locationName": null,
                            "slaGroupName": null,
                            "departmentName": null,
                            "projectName": null,
                            "handlerName": null,
                            "operatorName": null,
                            "mngPrimaryName": null,
                            "mngSecondaryName": null,
                            "mngTertiaryName": null,
                            "createdByName": null,
                            "updatedByName": null,
                            "auth": null,
                            "removed": false
                        },
                        "customCode": {
                            "id": 1,
                            "name": null,
                            "parent": null,
                            "description": null,
                            "hasSignature": null,
                            "orders": null,
                            "children": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "isRemoved": null
                        },
                        "value": null,
                        "isRemoved": false,
                        "keyString": 1,
                        "valueString": "서버"
                    },
                    {
                        "asset": {
                            "id": 317,
                            "assetName": null,
                            "assetCode": null,
                            "images": null,
                            "files": null,
                            "group": null,
                            "etc": null,
                            "task": null,
                            "location": null,
                            "slaGroup": null,
                            "department": null,
                            "project": null,
                            "operator": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "handler": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "endOfService": null,
                            "endOfServiceDiff": null,
                            "involvedIntoCompose": false,
                            "mngPrimary": null,
                            "mngSecondary": null,
                            "mngTertiary": null,
                            "importDate": null,
                            "importPrice": null,
                            "mngPrice": null,
                            "mngRate": null,
                            "assetFields": null,
                            "assetCustomCodes": null,
                            "assetCustomStrings": null,
                            "groupName": null,
                            "taskName": null,
                            "locationName": null,
                            "slaGroupName": null,
                            "departmentName": null,
                            "projectName": null,
                            "handlerName": null,
                            "operatorName": null,
                            "mngPrimaryName": null,
                            "mngSecondaryName": null,
                            "mngTertiaryName": null,
                            "createdByName": null,
                            "updatedByName": null,
                            "auth": null,
                            "removed": false
                        },
                        "customCode": {
                            "id": 146,
                            "name": null,
                            "parent": null,
                            "description": null,
                            "hasSignature": null,
                            "orders": null,
                            "children": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "isRemoved": null
                        },
                        "value": null,
                        "isRemoved": false,
                        "keyString": 146,
                        "valueString": "3.3.3.3"
                    }
                ],
                "assetCustomStrings": [],
                "groupName": "DBMS",
                "taskName": "계정계",
                "locationName": null,
                "slaGroupName": "3등급",
                "departmentName": null,
                "projectName": "통합ITO",
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": "아이티센씨티에스",
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "장성윤",
                "updatedByName": "관리자",
                "auth": null,
                "removed": false
            },
            {
                "id": 280,
                "assetName": "Cisco Nexus 93600CD-GX",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": "데이터센터 집선L3스위치",
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [
                    {
                        "id": 4,
                        "username": null,
                        "name": "이영희",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    },
                    {
                        "id": 5,
                        "username": null,
                        "name": "최수진",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    },
                    {
                        "id": 6,
                        "username": null,
                        "name": "강준호",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    },
                    {
                        "id": 7,
                        "username": null,
                        "name": "장미진",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    },
                    {
                        "id": 8,
                        "username": null,
                        "name": "김도훈",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    }
                ],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-04-27 15:38:25",
                "endOfService": "2025-09-12 00:00:00",
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": "2025-06-17 00:00:00",
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [
                    {
                        "asset": {
                            "id": 280,
                            "assetName": null,
                            "assetCode": null,
                            "images": null,
                            "files": null,
                            "group": null,
                            "etc": null,
                            "task": null,
                            "location": null,
                            "slaGroup": null,
                            "department": null,
                            "project": null,
                            "operator": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "handler": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "endOfService": null,
                            "endOfServiceDiff": null,
                            "involvedIntoCompose": false,
                            "mngPrimary": null,
                            "mngSecondary": null,
                            "mngTertiary": null,
                            "importDate": null,
                            "importPrice": null,
                            "mngPrice": null,
                            "mngRate": null,
                            "assetFields": null,
                            "assetCustomCodes": null,
                            "assetCustomStrings": null,
                            "groupName": null,
                            "taskName": null,
                            "locationName": null,
                            "slaGroupName": null,
                            "departmentName": null,
                            "projectName": null,
                            "handlerName": null,
                            "operatorName": null,
                            "mngPrimaryName": null,
                            "mngSecondaryName": null,
                            "mngTertiaryName": null,
                            "createdByName": null,
                            "updatedByName": null,
                            "auth": null,
                            "removed": false
                        },
                        "customCode": {
                            "id": 1,
                            "name": null,
                            "parent": null,
                            "description": null,
                            "hasSignature": null,
                            "orders": null,
                            "children": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "isRemoved": null
                        },
                        "value": null,
                        "isRemoved": false,
                        "keyString": 1,
                        "valueString": "네트워크장비"
                    }
                ],
                "assetCustomStrings": [],
                "groupName": "네트워크 장비",
                "taskName": "인프라",
                "locationName": "판교 오피스",
                "slaGroupName": "1등급",
                "departmentName": "인프라",
                "projectName": "신년 프로젝트",
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": "프롬소프트",
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "최현복",
                "updatedByName": null,
                "auth": null,
                "removed": false
            },
            {
                "id": 279,
                "assetName": "Samsung DDR5 16GB 4800MHz",
                "assetCode": "26",
                "images": null,
                "files": null,
                "group": null,
                "etc": "test\n\n123",
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [
                    {
                        "id": 6,
                        "username": null,
                        "name": "강준호",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    },
                    {
                        "id": 7,
                        "username": null,
                        "name": "장미진",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    },
                    {
                        "id": 8,
                        "username": null,
                        "name": "김도훈",
                        "email": null,
                        "phoneNumber": null,
                        "officeNumber": null,
                        "userGroup": null,
                        "department": null,
                        "company": null,
                        "pmInCharge": null,
                        "roles": null,
                        "position": null,
                        "employeeNumber": null,
                        "profileImage": null,
                        "signatureImage": null,
                        "serviceReceiveAuthority": false,
                        "emailReceiveAuthority": false,
                        "usePeriodDate": null,
                        "usePeriodDateKor": null,
                        "createdAt": null,
                        "updatedAt": null,
                        "auth": null
                    }
                ],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-04-27 15:37:54",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [
                    {
                        "id": null,
                        "asset": {
                            "id": 279,
                            "assetName": null,
                            "assetCode": null,
                            "images": null,
                            "files": null,
                            "group": null,
                            "etc": null,
                            "task": null,
                            "location": null,
                            "slaGroup": null,
                            "department": null,
                            "project": null,
                            "operator": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "handler": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "endOfService": null,
                            "endOfServiceDiff": null,
                            "involvedIntoCompose": false,
                            "mngPrimary": null,
                            "mngSecondary": null,
                            "mngTertiary": null,
                            "importDate": null,
                            "importPrice": null,
                            "mngPrice": null,
                            "mngRate": null,
                            "assetFields": null,
                            "assetCustomCodes": null,
                            "assetCustomStrings": null,
                            "groupName": null,
                            "taskName": null,
                            "locationName": null,
                            "slaGroupName": null,
                            "departmentName": null,
                            "projectName": null,
                            "handlerName": null,
                            "operatorName": null,
                            "mngPrimaryName": null,
                            "mngSecondaryName": null,
                            "mngTertiaryName": null,
                            "createdByName": null,
                            "updatedByName": null,
                            "auth": null,
                            "removed": false
                        },
                        "code": null,
                        "value": null,
                        "isRemoved": false,
                        "keyString": 1,
                        "valueString": "444"
                    },
                    {
                        "id": null,
                        "asset": {
                            "id": 279,
                            "assetName": null,
                            "assetCode": null,
                            "images": null,
                            "files": null,
                            "group": null,
                            "etc": null,
                            "task": null,
                            "location": null,
                            "slaGroup": null,
                            "department": null,
                            "project": null,
                            "operator": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "handler": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "endOfService": null,
                            "endOfServiceDiff": null,
                            "involvedIntoCompose": false,
                            "mngPrimary": null,
                            "mngSecondary": null,
                            "mngTertiary": null,
                            "importDate": null,
                            "importPrice": null,
                            "mngPrice": null,
                            "mngRate": null,
                            "assetFields": null,
                            "assetCustomCodes": null,
                            "assetCustomStrings": null,
                            "groupName": null,
                            "taskName": null,
                            "locationName": null,
                            "slaGroupName": null,
                            "departmentName": null,
                            "projectName": null,
                            "handlerName": null,
                            "operatorName": null,
                            "mngPrimaryName": null,
                            "mngSecondaryName": null,
                            "mngTertiaryName": null,
                            "createdByName": null,
                            "updatedByName": null,
                            "auth": null,
                            "removed": false
                        },
                        "code": null,
                        "value": null,
                        "isRemoved": false,
                        "keyString": 2,
                        "valueString": "2312"
                    },
                    {
                        "id": null,
                        "asset": {
                            "id": 279,
                            "assetName": null,
                            "assetCode": null,
                            "images": null,
                            "files": null,
                            "group": null,
                            "etc": null,
                            "task": null,
                            "location": null,
                            "slaGroup": null,
                            "department": null,
                            "project": null,
                            "operator": null,
                            "createdBy": null,
                            "updatedBy": null,
                            "handler": null,
                            "createdAt": null,
                            "updatedAt": null,
                            "endOfService": null,
                            "endOfServiceDiff": null,
                            "involvedIntoCompose": false,
                            "mngPrimary": null,
                            "mngSecondary": null,
                            "mngTertiary": null,
                            "importDate": null,
                            "importPrice": null,
                            "mngPrice": null,
                            "mngRate": null,
                            "assetFields": null,
                            "assetCustomCodes": null,
                            "assetCustomStrings": null,
                            "groupName": null,
                            "taskName": null,
                            "locationName": null,
                            "slaGroupName": null,
                            "departmentName": null,
                            "projectName": null,
                            "handlerName": null,
                            "operatorName": null,
                            "mngPrimaryName": null,
                            "mngSecondaryName": null,
                            "mngTertiaryName": null,
                            "createdByName": null,
                            "updatedByName": null,
                            "auth": null,
                            "removed": false
                        },
                        "code": null,
                        "value": null,
                        "isRemoved": false,
                        "keyString": 6,
                        "valueString": "123"
                    }
                ],
                "groupName": "업무소프트웨어",
                "taskName": null,
                "locationName": "판교 오피스",
                "slaGroupName": null,
                "departmentName": "인프라",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": "관리자",
                "auth": null,
                "removed": false
            },
            {
                "id": 278,
                "assetName": "Samsung DDR5 16GB 4800MHz_1",
                "assetCode": "23_1",
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-05-07 14:32:20",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": "100000",
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "웹 개발",
                "locationName": "판교 오피스",
                "slaGroupName": "4등급",
                "departmentName": "인프라",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": "관리자",
                "auth": null,
                "removed": false
            },
            {
                "id": 277,
                "assetName": "Seagate Barracuda 1TB 7200RPM SATA 6Gb/s_1",
                "assetCode": "   ",
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2025-06-19 13:31:17",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "서버관리",
                "locationName": "1층",
                "slaGroupName": null,
                "departmentName": "데브옵스",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": "관리자",
                "auth": null,
                "removed": false
            },
            {
                "id": 276,
                "assetName": "Seagate IronWolf 4TB NAS Hard Drive_1",
                "assetCode": "24",
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 17:41:53",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "네트워크 관리",
                "locationName": "로비",
                "slaGroupName": null,
                "departmentName": "본사",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": "관리자",
                "auth": null,
                "removed": false
            },
            {
                "id": 275,
                "assetName": "WD Blue 2TB 5400RPM SATA 6Gb/s_1",
                "assetCode": "25",
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2025-06-18 16:10:51",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "보안관리",
                "locationName": "소회의실 A",
                "slaGroupName": null,
                "departmentName": "IT운영부",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": "관리자",
                "auth": null,
                "removed": false
            },
            {
                "id": 274,
                "assetName": "WD Black 4TB 7200RPM High-Performance HDD_1",
                "assetCode": "22",
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2025-06-18 16:12:14",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "웹 개발",
                "locationName": "소회의실 B",
                "slaGroupName": null,
                "departmentName": "네트워크팀",
                "projectName": "신년 프로젝트",
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": "(주)고객",
                "mngSecondaryName": "그린테크",
                "mngTertiaryName": "화이트엔터프라이즈",
                "createdByName": "관리자",
                "updatedByName": "관리자",
                "auth": null,
                "removed": false
            },
            {
                "id": 273,
                "assetName": "Toshiba Canvio Basics 1TB Portable External HDD_1",
                "assetCode": "23_2",
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2025-06-18 16:11:38",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "모바일 앱 개발",
                "locationName": "2층 개발실",
                "slaGroupName": null,
                "departmentName": "보안팀",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": "관리자",
                "auth": null,
                "removed": false
            },
            {
                "id": 272,
                "assetName": "Toshiba X300 8TB 7200RPM SATA HDD_1",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 16:56:58",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "데이터 분석",
                "locationName": "개발팀 구역",
                "slaGroupName": null,
                "departmentName": "서버관리팀",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": "프롬소프트",
                "mngSecondaryName": "그린테크",
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": "관리자",
                "auth": null,
                "removed": false
            },
            {
                "id": 271,
                "assetName": "Seagate Barracuda 1TB 7200RPM SATA 6Gb/s_2",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 16:56:58",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "서버관리",
                "locationName": "회의실 201",
                "slaGroupName": null,
                "departmentName": "경영지원부",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": null,
                "auth": null,
                "removed": false
            },
            {
                "id": 270,
                "assetName": "Seagate IronWolf 4TB NAS Hard Drive_2",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 16:56:58",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "네트워크 관리",
                "locationName": "테스트 서버실",
                "slaGroupName": null,
                "departmentName": "인사팀",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": null,
                "auth": null,
                "removed": false
            },
            {
                "id": 269,
                "assetName": "WD Blue 2TB 5400RPM SATA 6Gb/s_2",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 16:56:58",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "보안관리",
                "locationName": "3층 전산실",
                "slaGroupName": null,
                "departmentName": "재무팀",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": null,
                "auth": null,
                "removed": false
            },
            {
                "id": 268,
                "assetName": "WD Black 4TB 7200RPM High-Performance HDD_2",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 16:56:58",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "웹 개발",
                "locationName": "서버 랙 R-01",
                "slaGroupName": null,
                "departmentName": "총무팀",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": null,
                "auth": null,
                "removed": false
            },
            {
                "id": 267,
                "assetName": "Toshiba Canvio Basics 1TB Portable External HDD_2",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 17:42:39",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "모바일 앱 개발",
                "locationName": "서버 랙 R-02",
                "slaGroupName": null,
                "departmentName": "전략기획부",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": null,
                "auth": null,
                "removed": false
            },
            {
                "id": 266,
                "assetName": "Toshiba X300 8TB 7200RPM SATA HDD_2",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 16:56:58",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "데이터 분석",
                "locationName": "네트워크 장비실",
                "slaGroupName": null,
                "departmentName": "사업기획팀",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": null,
                "auth": null,
                "removed": false
            },
            {
                "id": 265,
                "assetName": "Seagate Barracuda 1TB 7200RPM SATA 6Gb/s_3",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 16:56:58",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "서버관리",
                "locationName": "AWS Seoul 리전",
                "slaGroupName": null,
                "departmentName": "시장분석팀",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": null,
                "auth": null,
                "removed": false
            },
            {
                "id": 264,
                "assetName": "Seagate IronWolf 4TB NAS Hard Drive_3",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 16:56:58",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "네트워크 관리",
                "locationName": "ap-northeast-2a (AZ)",
                "slaGroupName": null,
                "departmentName": "신사업개발팀",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": null,
                "mngSecondaryName": null,
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": null,
                "auth": null,
                "removed": false
            },
            {
                "id": 263,
                "assetName": "WD Blue 2TB 5400RPM SATA 6Gb/s_3",
                "assetCode": null,
                "images": null,
                "files": null,
                "group": null,
                "etc": null,
                "task": null,
                "location": null,
                "slaGroup": null,
                "department": null,
                "project": null,
                "operator": [],
                "createdBy": null,
                "updatedBy": null,
                "handler": [],
                "createdAt": "2026-01-01 00:00:00",
                "updatedAt": "2026-02-03 16:56:58",
                "endOfService": null,
                "endOfServiceDiff": null,
                "involvedIntoCompose": false,
                "mngPrimary": null,
                "mngSecondary": null,
                "mngTertiary": null,
                "importDate": null,
                "importPrice": null,
                "mngPrice": null,
                "mngRate": null,
                "assetFields": null,
                "assetCustomCodes": [],
                "assetCustomStrings": [],
                "groupName": "서버(물리)",
                "taskName": "보안관리",
                "locationName": "Production VPC",
                "slaGroupName": null,
                "departmentName": "부산지사",
                "projectName": null,
                "handlerName": null,
                "operatorName": null,
                "mngPrimaryName": "화이트엔터프라이즈",
                "mngSecondaryName": "그린테크",
                "mngTertiaryName": null,
                "createdByName": "관리자",
                "updatedByName": "관리자",
                "auth": null,
                "removed": false
            }
        ]
    }
    const headerApi = useCallback(async (_payload: HeaderState[]) => {
        await new Promise<void>((r) => window.setTimeout(r, 300));
        return true as const;
    }, []);

    const onHeaderSave = useCallback(
        async (payload: HeaderState[]) => {
            await headerApi(payload);
            setHeader((prev) => applyHeaderStateToHeader({ header: prev, state: payload }));
        },
        [headerApi],
    );
    const onUploadFiles = useCallback(async (files: File[]) => {
        await new Promise((r) => setTimeout(r, 1500));
        console.log(
            "업로드 완료 샘플",
            files.map((f) => ({ name: f.name, size: f.size, type: f.type })),
        );
    }, []);
    const onHeaderReset = useCallback(() => console.log("reset clicked"), []);
    const onDownloadClick = useCallback(() => console.log("download Clicked"), []);
    const onCreateClick = useCallback(() => console.log("create"), []);
    // api 요청 테스트용 삭제 메서드
    const deleteApi = useCallback((ids: number[]) =>
        new Promise<void>((resolve) => {
            console.log("delete 요청", ids);
            window.setTimeout(() => resolve(), 1000);
        }), []);

    const onDeleteClick = useCallback(async (rows: unknown[]) => {
        const ids = rows
            .map((r) => (r as { id?: unknown }).id)
            .filter((id): id is number => typeof id === "number" && Number.isFinite(id));
        if (ids.length === 0) return;

        await deleteApi(ids);
        // 실제 서비스라면 여기서 서버 재조회 후 `setData`를 한다.
        console.log("삭제 완료, 이후 재조회 필요", ids);
    }, [deleteApi]);


    const onRowClick = useCallback((rows: unknown) => console.log("rowClick", rows), []);
    const onPageChange = useCallback((p: any) => {
        console.log("pageable", p);
        setPageNumber(p.pageNumber ?? 0);
    }, []);

    const pageData = useMemo(() => {
        const rows = Array.isArray(data) ? data : (data as { content?: unknown[] }).content ?? [];
        return {
            content: rows,
            pageable: {pageNumber, pageSize: PAGE_SIZE, size: PAGE_SIZE},
            totalElements: TOTAL_ELEMENTS,
            totalPages: TOTAL_PAGES,
        };
    }, [data, pageNumber]);

    const isAdmin = true

    return (
        <div style={{height:'700px', width:'1400px', paddingLeft:'10px'}}>
            <JsGrid
                resizable={true}
                theme={'linear'}
                // style={{flex: "1 1 0%", minHeight: 0, width: "100%"}}
                header={header}
                data={pageData}
                onHeaderSave={isAdmin ? onHeaderSave : undefined}
                onUploadFiles={isAdmin ? onUploadFiles : undefined}
                onHeaderReset={onHeaderReset}
                onDownloadClick={isAdmin ? onDownloadClick : undefined}
                onCreateClick={isAdmin ? onCreateClick : undefined}
                onDeleteClick={isAdmin ? onDeleteClick : undefined}
                onRowClick={onRowClick}
                onPageChange={onPageChange}
            />
        </div>
    );
};

export default App;